# Generated by Django 3.2 on 2022-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='lang',
            field=models.CharField(default='uz', max_length=10),
            preserve_default=False,
        ),
    ]
